### ISSUE TITLE
Starting a timer with a new entry leaves it stuck at zero

### ISSUE THREAD

**Issue by grayside** [phase2/openair-reborn#20]
I am finding the timer mode (hitting start when a new entry does not have "Hours" filled in), creates a new entry at zero without any incrementation. I find it necessary to pause and restart the timer with the play/pause button in the entry operations links.
This has been the case since I first installed Reborn.

Console Output

```
TypeError: Cannot read property 'start' of undefined
    at chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/scripts/timeentry.js:1:727
    at Array.forEach (native)
    at Object.f [as forEach] (chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/angular/angular.js:1:1006)
    at k.a.addTime (chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/scripts/timeentry.js:1:260)
    at chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/angular/angular.js:3:29629
    at chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/angular/angular.js:4:4819
    at k.$eval (chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/angular/angular.js:2:25863)
    at k.$apply (chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/angular/angular.js:2:26141)
    at HTMLInputElement.<anonymous> (chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/angular/angular.js:4:4801)
    at HTMLInputElement._.event.dispatch (chrome-extension://ajmdofceiiflcdlclkicifcnccdgkcmb/bower_components/jquery/dist/jquery.js:2:14424) 
```

**Comment by grayside** [comment]
Two additional notes:
- This happens on mouse click, not on hitting enter.
- The time on the entry displays as zero, but the summed time for the day displays as NaN.

**Comment by crittermike** [comment]
I'm not able to reproduce this one anymore.
